<?php

/**
 * This is the model base class for the table "comentario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Comentario".
 *
 * Columns in table "comentario" available as properties of the model,
 * followed by relations of table "comentario" available as properties of the model.
 *
 * @property integer $id_comentario
 * @property string $nome_autor
 * @property string $comentario
 * @property integer $id_post
 *
 * @property Post $idPost
 */
abstract class BaseComentario extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'comentario';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Comentario|Comentarios', $n);
	}

	public static function representingColumn() {
		return 'nome_autor';
	}

	public function rules() {
		return array(
			array('nome_autor, comentario, id_post', 'required'),
			array('id_post', 'numerical', 'integerOnly'=>true),
			array('nome_autor', 'length', 'max'=>255),
			array('id_comentario, nome_autor, comentario, id_post', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idPost' => array(self::BELONGS_TO, 'Post', 'id_post'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_comentario' => Yii::t('app', 'Id Comentario'),
			'nome_autor' => Yii::t('app', 'Nome Autor'),
			'comentario' => Yii::t('app', 'Comentario'),
			'id_post' => null,
			'idPost' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_comentario', $this->id_comentario);
		$criteria->compare('nome_autor', $this->nome_autor, true);
		$criteria->compare('comentario', $this->comentario, true);
		$criteria->compare('id_post', $this->id_post);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}